# Generated by Django 5.2 on 2025-05-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='publicado',
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('PR', 'Por leer'), ('LE', 'Leyendo'), ('LD', 'Leído')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='resena',
            field=models.TextField(blank=True),
        ),
    ]
